name: arbor-ip
version: '1.0.0'
category: Data
author: Arbor Networks
maintainer: mayhem@arbor.net
copyright: Arbor Networks
license: MIT
github: packetloop/arbor-ip
description: something something something something something
synopsis: something
extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - Arbor.Network.Ip
  dependencies:
  - base >=4.7 && <5
  - deepseq

tests:
  arbor-ip-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - arbor-ip
    - hedgehog
    - hspec
    - hw-hspec-hedgehog
