resolver: lts-10.9

packages:
- '.'
- location:
    git: https://github.com/haskell-works/hw-hspec-hedgehog
    commit: 1b12be24895bb386340547ea3e439f0080f622a3
  extra-dep: true

extra-deps:
- hedgehog-0.5.3

# Override default flag values for local packages and extra-deps
flags: {}

extra-package-dbs: []
